### ISSUE TITLE
Players Don't Die in the void

### ISSUE THREAD

**Issue by real-tonda** [encodeous/MissileWarsX#4]
When a player jumps into the void, they don't die.

Plugin List:
(10)
Essentials, FAWE, LuckPerms, MissileWarsX, PlaceholderAPI, ProtocolLib, ServerSelectorX-Connector, ViaBackwards, ViaRewind, ViaVersion

**Comment by encodeous** [comment]
Fixed in [260f947](https://github.com/encodeous/MissileWarsX/commit/260f947948313c5014ac4c244c12ec504e643876)!

Thanks for the report :)
